accelerate launch finetune.py \
    --base_model meta-llama/Llama-2-70b-hf \
    --data-path ./merged_and_cleaned3.json \
    --output_dir ./llama2-platypus-70b \
    --batch_size 12 \
    --micro_batch_size 1 \
    --num_epochs 1 \
    --learning_rate 0.0002 \
    --cutoff_len 4096 \
    --val_set_size 0 \
    --lora_r 16 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --lora_target_modules '[q_proj, k_proj, v_proj, o_proj]' \
    --train_on_inputs False \
    --add_eos_token False \
    --group_by_length False \
    --prompt_template_name alpaca \
    --lr_scheduler 'linear' \
    --warmup_steps 100